apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  DATABASE_HOST: "postgres.default.svc.cluster.local"
  DATABASE_USER: "app_user"
  DATABASE_PASSWORD: "supersecret123"
